version: '3.3'

services:

   wordpress:
     #build: ./wp
     image: kosyiev/wp_server:latest
     ports:
       - 8080:80
       - 443:443
     volumes:
       - wp_vol:/var/www/html
     restart: always
     links:
       - mysql_server

   mysql_server :
     #build: ./db
     image: kosyiev/db_server:latest
     ports:
       - 3306:3306
     volumes:
       - db_vol:/var/lib/mysql
     restart: always

volumes:
  db_vol:
  wp_vol:
