Vagrant.configure("2") do |config|

  config.vm.define "ubuntu" do |ubuntu|
   
    ubuntu.vm.box = "ubuntu/bionic64"

    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory ="4096"
      vb.cpus = "2"
    end

    ubuntu.vm.network :forwarded_port, guest: 8090, host: 8090
    ubuntu.vm.network :forwarded_port, guest: 8080, host: 8080
    ubuntu.vm.network :forwarded_port, guest: 3306, host: 3306
    config.vm.synced_folder "./mysql/", "/home/vagrant/mysql"
    config.vm.synced_folder "./wordpress/", "/home/vagrant/wordpress"
#   ubuntu.vm.provision :shell, path: "confluence.sh"
    ubuntu.vm.provision :shell, path: "docker_setup.sh"


  end

end

