Vagrant.configure("2") do |config|

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
    ubuntu.vm.network :forwarded_port, guest: 8090, host: 8080
    ubuntu.vm.network :forwarded_port, guest: 3306, host: 3306
    ubuntu.vm.provision "shell", inline: $mysql_install
    ubuntu.vm.provision "shell", inline: $confluence_install
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory ="4096"
      vb.cpus = "2"
    end
  end

end

  $mysql_install = <<-SCRIPT
    apt -y update
    DEBIAN_FRONTEND=noninteractive apt-get -y install mysql-server     #install mysql-server in silent mode
    echo "SET PASSWORD FOR 'root'@'localhost' = '12346';" | mysql
    echo "CREATE DATABASE CONFLUENSE;" | mysql                         #create new DB
  SCRIPT

  $confluence_install = <<-SCRIPT
    apt -y update
    apt install -y default-jre
    #wget https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.3.1-x64.bin
    mkdir /var/confluence-home
    echo "app.confHome=/var/confluence_home				#set configuration for confluence installation
app.install.service$Boolean=true
portChoice=default
launch.application$Boolean=true
sys.adminRights$Boolean=true
sys.confirmedUpdateInstallationString=false
sys.installationDir=/opt/atlassian/confluence6_15_5
sys.languageId=en" >> response.varfile
    chmod +x atlassian-confluence-7.3.1-x64.bin
    ./atlassian-confluence-7.3.1-x64.bin -q -varfile response.varfile
  SCRIPT

